### ISSUE TITLE
Update ros-tooling/reviewers codeowners/team

### ISSUE THREAD

**Issue by christophebedard** [ros-tooling/.github#6]
The `@ros-tooling/reviewers` team is set as the codeowner for all the repos in this org: https://github.com/orgs/ros-tooling/teams/reviewers. However, some of the people are not active here anymore: @gbiggs @jhdcs. We should remove them, because it just creates unnecessary notifications for them, and, if they get randomly assigned PRs to review, contributors end up pinging them and don't really get a reply.

I personally cannot remove people. @emersonknapp @clalancette I believe you can. We can discuss first, of course.

I opened an issue in this repo because that seemed to be the most appropriate given that there is a "default" CODEOWNERS file here: https://github.com/ros-tooling/.github/blob/master/.github/CODEOWNERS

**Comment by emersonknapp** [comment]
thanks for bringing this up! for future reference https://github.com/ros-tooling/community is the repo where we manage this stuff. I think it even has issue templates for exactly this use case

**Comment by emersonknapp** [comment]
but anyways, done.

**Comment by christophebedard** [comment]
Yeah, good point.

Thanks!
